server:
  port: 10011
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
  application:
    name: wechat-server-provider

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    instance-id: wechat-server-provider   #将自己的该名字注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true     #访问路径可以显示IP地址
